<a href="https://colab.research.google.com/github/19PA1A0282/AI-Lab/blob/master/Exp_1_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Experiment : 1 NumPy

## i) Different ways to create NumPy Arrays

### a) Create a NumPy Array using List




In [ ]:
#Let's create a different ways of numpy arrays

import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

### b) Create a NumPy array using Arrange

In [ ]:
b = np.arange( 4 )
b

array([0, 1, 2, 3])

## ii) Add, Remove, Modify elements in an array

In [ ]:
#Let's write a program to add elements in array

import numpy as np
x=np.array([10,20,30,40,50,60])
np.append(x,[[7,8,9]])

array([10, 20, 30, 40, 50, 60,  7,  8,  9])

In [ ]:
#Let's write a program to delete elements in array

import numpy as np
x=np.array([10,20,30,40,50,60])
index=[0,3,4]
x1=np.delete(x,index)
x1

array([20, 30, 60])

In [ ]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.ndim

2

In [ ]:
a.sum()

105

In [ ]:
a.sum(axis=0)

array([15, 18, 21, 24, 27])

In [ ]:
a.sum(axis=1)

array([10, 35, 60])

## iii) Arithmetic operations on NumPy array

In [ ]:
#Let's write a program for arithmetic operation on numpy array

a = np.array( [20,30,40,50] )
b = np.arange( 4 )
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [ ]:
c = a-b #Simple substraction
print(c)

[20 29 38 47]


In [ ]:
print(b**2) #Scalar multiplication(power)

[0 1 4 9]


In [ ]:
print(10*np.sin(a)) #Trignometric functions are available in numpy package

[ 9.12945251 -9.88031624  7.4511316  -2.62374854]


In [ ]:
print(a<35) #Retuns true (or) false based on condition

[ True  True False False]


In [ ]:
a[0] +=10 #This is equalient to a[0]=a[0]+10
print(a)

[30 30 40 50]


## iv) Slicing and iterating of NumPy arrays

### a) Slicing of NumPy arrays

In [ ]:
#Let's write a program for slicing of numpy arrays

a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b=a[:1,:2]
b

array([[1, 2]])

### b) Iterating of Numpy arrays

In [ ]:
#Let's write a program for iterating of numpy array

a=np.arange(12).reshape(4,3)**2
print(a)
for i in a:
  print(i)

[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]
[0 1 4]
[ 9 16 25]
[36 49 64]
[ 81 100 121]


## v) Matrix operations on NumPy arrays

In [ ]:
#Let's write a program on matrix operations numpy arrays

import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])